//Route
export const IS_DRAWER_OPEN = 'IS_DRAWER_OPEN';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';

//Auth
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';

//Home
export const ALL_SLIDERS = 'ALL_SLIDERS';
export const ALL_SLIDERS_LOADING = 'ALL_SLIDERS_LOADING';
export const LAST_POSTS = 'LAST_POSTS';
export const LAST_POSTS_LOADING = 'LAST_POSTS_LOADING';
export const DISCOUNT_POSTS = 'DISCOUNT_POSTS';
export const DISCOUNT_POSTS_LOADING = 'DISCOUNT_POSTS_LOADING';

//Search
export const SEARCH_POSTS = 'SEARCH_POSTS';

//Categories
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const GET_ALL_CATEGORY_POSTS = 'GET_ALL_CATEGORY_POSTS';
export const POST_ONE_CATEGORY = 'POST_ONE_CATEGORY';
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';
export const UPDATE_ONE_CATEGORY = 'UPDATE_ONE_CATEGORY';
export const DELETE_ONE_CATEGORY = 'DELETE_ONE_CATEGORY';