//Route
export const IS_DRAWER_OPEN = 'IS_DRAWER_OPEN';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';

//Auth
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

//Sliders
export const SLIDERS_LOADING = 'SLIDERS_LOADING';
export const GET_ALL_SLIDERS = 'GET_ALL_SLIDERS';
export const POST_ONE_SLIDER = 'POST_ONE_SLIDER';
export const GET_ONE_SLIDER = 'GET_ONE_SLIDER';
export const UPDATE_ONE_SLIDER = 'UPDATE_ONE_SLIDER';
export const DELETE_ONE_SLIDER = 'DELETE_ONE_SLIDER';

//Search
export const SEARCH_POSTS = 'SEARCH_POSTS';

//Categories
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const GET_ALL_CATEGORY_POSTS = 'GET_ALL_CATEGORY_POSTS';
export const POST_ONE_CATEGORY = 'POST_ONE_CATEGORY';
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';
export const UPDATE_ONE_CATEGORY = 'UPDATE_ONE_CATEGORY';
export const DELETE_ONE_CATEGORY = 'DELETE_ONE_CATEGORY';

//Cities
export const CITIES_LOADING = 'CITIES_LOADING';
export const GET_ALL_CITIES = 'GET_ALL_CITIES';
export const GET_ONE_CITY = 'GET_ONE_CITY';
export const POST_ONE_CITY = 'POST_ONE_CITY';
export const UPDATE_ONE_CITY = 'UPDATE_ONE_CITY';
export const DELETE_ONE_CITY = 'DELETE_ONE_CITY';

//Comments
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const GET_ALL_COMMENTS_PER_USER = 'GET_ALL_COMMENTS_PER_USER';
export const GET_ALL_COMMENTS_PER_POST = 'GET_ALL_COMMENTS_PER_POST';
export const GET_ONE_COMMENTS = 'GET_ONE_COMMENTS';
export const POST_ONE_COMMENTS = 'POST_ONE_COMMENTS';
export const UPDATE_ONE_COMMENTS = 'UPDATE_ONE_COMMENTS';
export const DELETE_ONE_COMMENTS = 'DELETE_ONE_COMMENTS';

//Favourites
export const FAVOURITES_LOADING = 'FAVOURITES_LOADING';
export const GET_ALL_FAVOURITES = 'GET_ALL_FAVOURITES';
export const GET_ONE_FAVOURITE = 'GET_ONE_FAVOURITE';
export const POST_ONE_FAVOURITE = 'POST_ONE_FAVOURITE';
export const DELETE_ONE_FAVOURITE = 'DELETE_ONE_FAVOURITE';

//Posts
export const POSTS_LOADING = 'POSTS_LOADING';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_MY_POSTS = 'GET_ALL_MY_POSTS';
export const GET_ONE_POST = 'GET_ONE_POST';
export const GET_LAST_POSTS = 'GET_LAST_POSTS';
export const GET_DISCOUNT_POSTS = 'GET_DISCOUNT_POSTS';
export const GET_RENT_POSTS = 'GET_RENT_POSTS';
export const UPDATE_ONE_POST = 'UPDATE_ONE_POST';
export const DELETE_ONE_POST = 'DELETE_ONE_POST';
export const POST_ONE_POST = 'POST_ONE_POST';
export const GET_ALL_POSTS_BY_CATEGORY = 'GET_ALL_POSTS_BY_CATEGORY';

//Sizes
export const SIZES_LOADING = 'SIZES_LOADING';
export const GET_ALL_SIZES = 'GET_ALL_SIZES';
export const GET_ONE_SIZE = 'GET_ONE_SIZE';
export const POST_ONE_SIZE = 'POST_ONE_SIZE';
export const UPDATE_ONE_SIZE = 'UPDATE_ONE_SIZE';
export const DELETE_ONE_SIZE = 'DELETE_ONE_SIZE';

//Users
export const USERS_LOADING = 'USERS_LOADING';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ONE_USER = 'GET_ONE_USER';
export const POST_ONE_USER = 'POST_ONE_USER';
export const UPDATE_ONE_USER = 'UPDATE_ONE_USER';
export const DELETE_ONE_USER = 'DELETE_ONE_USER';
export const GET_MY_PROFILE = 'GET_MY_PROFILE'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';